// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiVcKPYtnX9p9M_0ZTe24_M-7shvFNWw4',
    appId: '1:123627311592:web:4543a8159f1aed03c4945d',
    messagingSenderId: '123627311592',
    projectId: 'maker-81caf',
    authDomain: 'maker-81caf.firebaseapp.com',
    storageBucket: 'maker-81caf.appspot.com',
    measurementId: 'G-B2XLYCSMS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJE4wg22YtR_yhiR8vUihNgh7jBT3kizY',
    appId: '1:123627311592:android:edac2c26b2675214c4945d',
    messagingSenderId: '123627311592',
    projectId: 'maker-81caf',
    storageBucket: 'maker-81caf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB59wddtvMLbfIbtTd0CZ_LmVXkQ0oJ__4',
    appId: '1:123627311592:ios:b42844b8b4c4e54bc4945d',
    messagingSenderId: '123627311592',
    projectId: 'maker-81caf',
    storageBucket: 'maker-81caf.appspot.com',
    iosBundleId: 'com.example.maker',
  );
}
